import esriConfig from "@arcgis/core/config";

esriConfig.apiKey = "AAPTaXXU9pkdJyzWN82CgjekyTQ..cTzStLypIU_ODDXKdJN7nxKNTBmmuN5pxouWsjXmFIV7z-KQx1oPAqmhOoKQyOLhxFbvRQbKCqqv0798InrQY7KJHHFxWp4D5bVkfyPqTvywG7Q07ZzpvyYGoCWFM4AOEZ2YtbQbf2X230qXRaDk_Q_4QVXh3ig_qAThMF6ZYB9Szu6xOWhfnBXLl-uqinTIo_RHWiOdUY1uUELe1HyvalLCaxhzLA7HBkRR-duOwOwbE-yqWN9XkEyvbEtYoPmF9D7gig..AT1_OEr9aTcB";

export default esriConfig;
